# Параметры модели
in_features: 60
dropout: 0.3

# Параметры обучения
epochs: 100
lr: 1e-3
batch_size: 64
num_workers: 4
log_every_n_steps: 10
early_stopping_threshold: 10

pos_weight: 38.0

optimizer_type: 'adamw'
scheduler_type: 'reduce_on_plateau'


reduce_on_plateau_params:
  patience: 10
  min_lr: 1e-6
  threshold: 1e-4

cosine_annealing_params:
  T_max: 10
  eta_min: 1e-6

one_cycle_params:
  steps_per_epoch: 100
  epochs: 30
  pct_start: 0.3
  div_factor: 25.0
  final_div_factor: 10000.0


sgd_params:
  weight_decay: 1e-5
  momentum: 0.9

adam_params:
  weight_decay: 1e-5

adamw_params:
  weight_decay: 1e-5


# Пути к датасетам
train_dataset_path: ../../../datasets/PlagiNet/
val_dataset_path: ../../../datasets/PlagiNet/
test_dataset_path: ../../../datasets/PlagiNet/
