# Параметры модели
hidden_size: 512
num_lstm_layers: 2
dropout: 0.3
bidirectional: true

# Параметры обучения
epochs: 100
lr: 1e-3
batch_size: 32
num_workers: 4
log_every_n_steps: 10
early_stopping_threshold: 10

frequency_weight: 0
class_weight: 0
offset_weight: 1
duration_weight: 1
eos_weight: 0.5

optimizer_type: 'adamw'
scheduler_type: 'reduce_on_plateau'


reduce_on_plateau_params:
  patience: 10
  min_lr: 1e-6
  threshold: 1e-4

cosine_annealing_params:
  T_max: 10
  eta_min: 1e-6

one_cycle_params:
  steps_per_epoch: 100
  epochs: 30
  pct_start: 0.3
  div_factor: 25.0
  final_div_factor: 10000.0

sgd_params:
  weight_decay: 1e-5
  momentum: 0.9

adam_params:
  weight_decay: 1e-5

adamw_params:
  weight_decay: 1e-5

# Пути к датасетам
train_dataset_path: ../../../datasets/melody_extraction/processed/train/
val_dataset_path: ../../../datasets/melody_extraction/processed/val/
test_dataset_path: ../../../datasets/melody_extraction/processed/test/
